input/pagecontent/index.md
- data quality
- integrity
- validation
=> FHIR-35920 - Data Quality Section

input/pagecontent/profiles.md, input/resources/StructureDefinition-medicationadministration-deqm.xml
Preview Branch:
https://build.fhir.org/ig/HL7/davinci-deqm/branches/fix-FHIR-37899/
=> FHIR-37899 - remove MedicationAdministration

input/data/ig.yml, input/examples/MeasureReport-ratio-measurereport01.json
Preview
https://build.fhir.org/ig/HL7/davinci-deqm/branches/FHIR-38073/
=> FHIR-38073 Add example MeasureReport for a ratio measure

input/examples/Endpoint-endpoint01.json
=> Added endpoint example

input/examples/Bundle-single-indv-vte-report-option1.json, input/examples/MedicationRequest-sde-nhsn-iip-add101-10.json, input/examples/sde-example-patient-data-bundle.json, input/ignoreWarnings.txt
-bundle-single-indv-vte-report-option1
-MedicationRequest-sde-nhsn-iip-add101-10
-sde-example-patient-data-bundle
-ignoreWarnings
=> Updated the following to remove warnings/info messages:

input/pagecontent/StructureDefinition-datax-measurereport-deqm-intro.md, input/pagecontent/datax.md, input/pagecontent/summary-reporting.md
FHIR-39979
FHIR-40112
FHIR-40132
FHIR-40133
=> DEQM IG Ballot Comments applied March 2023

input/examples/GuidanceResponse-guidanceresponse01.json, input/resources/StructureDefinition-reasonDetail.json
Replaced example content and removed "GuidanceResponse.dataRequirement" expression from reasondetail
=> FHIR-40803 reasondetail change + example change

input/data/package_list.yml, input/pagecontent/change-notes.md, input/resources/StructureDefinition-extension-reportingProgram.json
Do this one AFTER FHIR-42954, please
=> Fhir 43321

input/pagecontent/guidance.md
https://jira.hl7.org/browse/FHIR-44577
=> FHIR-44577

input/data/package_list.yml, input/pagecontent/change-notes.md, input/pagecontent/summary-reporting.md
https://jira.hl7.org/browse/FHIR-44570
=> FHIR-44570 Summary measure reporting typo

input/data/package_list.yml, input/pagecontent/change-notes.md, input/pagecontent/mrp.md, input/pagecontent/vte1.md
https://jira.hl7.org/browse/FHIR-44572
=> FHIR-44572 DEQM Practitioner References

input/data/package_list.yml, input/pagecontent/change-notes.md, input/resources/OperationDefinition-care-gaps.xml, input/resources/OperationDefinition-deqm.evaluate-measure.xml, input/resources/StructureDefinition-datax-measurereport-deqm.xml, input/resources/StructureDefinition-indv-measurereport-deqm.xml, input/resources/StructureDefinition-subjectlist-measurereport-deqm.xml, input/resources/StructureDefinition-summary-measurereport-deqm.xml
3 commits, 1 for each tracker, plus one for change log edits
=> FHIR-45430, FHIR-31416

input/resources/StructureDefinition-subjectlist-measurereport-deqm.xml
https://jira.hl7.org/browse/FHIR-46239
=> FHIR-46239 .measureScore to 0..1

input/pagecontent/guidance.md
https://jira.hl7.org/browse/FHIR-46372
=> FHIR-46372 add new top-level section

input/includes/link-list.md, input/pagecontent/guidance.md, input/pagecontent/vte1.md
https://jira.hl7.org/browse/FHIR-44571
=> Fhir 44571

input/examples/GuidanceResponse-detailedguidanceresponse01.json, input/examples/GuidanceResponse-detailedguidanceresponse02.json
QA for GuidanceResponse-detailedguidanceresponse01.json and GuidanceResponse-detailedguidanceresponse02.json
=> guidance examples qa changes

input/examples/Bundle-multiple-indv-mrp-obs-report.json
- Pointing at http://hl7.org/fhir/us/qicore/StructureDefinition/qicore-simple-observation instead of http://hl7.org/fhir/us/qicore/StructureDefinition/qicore-observation
- Updated NPI entries to be 10 digit
=> Adjusted indv-mrp-obs-report 

input/examples/Bundle-single-indv-col-obs-report.json
Remain slice errors due to MeasureReport profile implementation.
=> QA Updated URLs and provided NPI number

input/examples/Bundle-single-indv-mrp-task-report.json
Added NPI numbers.
I see that the slice errors all went away.
=> QA Added proper NPI numbers.

input/examples/MeasureReport-indv-measurereport02.json
=> MeasureReport-indv-measurereport02

input/examples/MeasureReport-summ-attestation.json
Removed subject as it is no longer allowed.
Updated scoring (at root level)
Updated references.
=> QA Fixed errors in MeasureReport-summ-attestation.json

input/examples/MeasureReport-summ-attestation.json, input/includes/link-list.md, input/pagecontent/col.md, input/pagecontent/datax.md, input/pagecontent/gaps-examples.md, input/pagecontent/indv-reporting.md, input/pagecontent/mrp.md, input/pagecontent/summary-reporting.md, input/pagecontent/vte1.md
[Summary](http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/summary-measurereport-deqm)  sets "subject" cardinality to 0..0
Therefore, removed subject from this example.
=> QA Removed subject from MeasureReport-summ-attestation.json again

input/pagecontent/StructureDefinition-datax-measurereport-deqm-intro.md
- Issue with entries that have path that end in .extension but have no sliceName
- Skipping fields like this
=> Generated Into: Skipping endsWith .extension without sliceName

input/includes/link-list.md
https://jira.hl7.org/browse/FHIR-47535
There isn't a qa.html reference that I can show a snippet from.
=> adjusted link to negation-in-fhir

input/pagecontent/change-notes.md, input/pagecontent/index.md
https://jira.hl7.org/browse/FHIR-48447
On index page - no snippet;
=> FHIR-48447 changed 'value based' to 'value-based'

input/resources/StructureDefinition-datax-measurereport-deqm.xml, input/resources/StructureDefinition-indv-measurereport-deqm.xml, input/resources/StructureDefinition-subjectlist-measurereport-deqm.xml, input/resources/StructureDefinition-summary-measurereport-deqm.xml
https://jira.hl7.org/browse/FHIR-47454
=> FHIR-47454 Consider modifying the definition of Must Support

input/examples/MeasureReport-summ-medicare-stratification-example.json, input/resources/Measure-stratifications.json
Added new measure and updated measure property to stratification example to point at it.
=> FHIR-47400: New measure in example

input/pagecontent/change-notes.md, input/resources/StructureDefinition-gaps-detectedissue-deqm.xml
https://jira.hl7.org/browse/FHIR-48758
=> FHIR-48758 Care Gaps Support for MultiRate Measures (revised)

input/pagecontent/change-notes.md, input/resources/StructureDefinition-indv-measurereport-deqm.xml, input/resources/StructureDefinition-summary-measurereport-deqm.xml
https://jira.hl7.org/browse/FHIR-50052
Note: There are warnings due to versions of profiles. In a discussion in Skype on this topic, Bryn stated "And I would say don't do anything about the version warnings until we're done making all the other changes."
=> FHIR-50052 remove MS from DEQM profiles

input/ig.json, input/pagecontent/change-notes.md
https://jira.hl7.org/browse/FHIR-49861
No image available from qa.html
=> FHIR-49861 update CQFM dependency to 5.0.0

input/pagecontent/StructureDefinition-datax-measurereport-deqm-intro.md, input/pagecontent/StructureDefinition-extension-careGapRemark-intro.md, input/pagecontent/StructureDefinition-extension-measureScoring-intro.md, input/pagecontent/StructureDefinition-gaps-bundle-deqm-intro.md, input/pagecontent/StructureDefinition-gaps-composition-deqm-intro.md, input/pagecontent/StructureDefinition-gaps-detectedissue-deqm-intro.md, input/pagecontent/StructureDefinition-gaps-group-deqm-intro.md, input/pagecontent/StructureDefinition-gaps-guidanceresponse-detailedcaregap-intro.md, input/pagecontent/StructureDefinition-indv-measurereport-deqm-intro.md, input/pagecontent/StructureDefinition-indv-measurereport-list-intro.md, input/pagecontent/StructureDefinition-reasonDetail-intro.md, input/pagecontent/StructureDefinition-subjectlist-measurereport-deqm-intro.md, input/pagecontent/StructureDefinition-summary-measurereport-deqm-intro.md
Parent rule: child elements not considered for condition if parent element is false in each condition
=> "Parent rule" enforcement

input/pagecontent/change-notes.md, input/pagecontent/profiles.md, input/resources/StructureDefinition-extension-careGapRemark.json
Updated Care Gap Remark to align with Condition Category Remark
=> FHIR-50210 - Updated Care Gap Remark to align with Condition Category Remark

input/pagecontent/StructureDefinition-gaps-detectedissue-deqm-intro.md, input/pagecontent/StructureDefinition-indv-measurereport-deqm-intro.md, input/pagecontent/StructureDefinition-parameters-caregap-remark-patch-intro.md, input/pagecontent/StructureDefinition-subjectlist-measurereport-deqm-intro.md, input/pagecontent/StructureDefinition-summary-measurereport-deqm-intro.md
Ran the intro generator against the latest master branch for Abdullah to review.
=> Intro generation  04/18/2025

input/examples/Bundle-single-gaps-closed-indv-report02.json, input/examples/Measure-pi-example.json, input/examples/MeasureReport-attestation-boolean.json, input/examples/MeasureReport-sde-example.json, input/examples/MeasureReport-summ-multirate.json, input/examples/Organization-ad-hoc-operation-input-example.json, input/examples/sde-example-artifact-bundle.json, input/ig.json, input/resources/OperationDefinition-care-gaps.xml
Additional fixes from qa.html - mostly errors.
=> Qa cleanup 3
